### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by julsemaan** [caesar0301/http-sniffer#2]
Hi,

First, loving the util, it's been offering performance that I very much appreciate while parsing a huge PCAP file

Only thing I saw is that the compiled binary uses 2 full CPUs when running on a live interface with extremelly limited traffic (sniffing only my workstation)

Don't see much happening in the strace though

strace :
http://pastebin.com/TXLjmu4E

Let me know if you need more info

Thanks !

**Comment by caesar0301** [comment]
There is a flow hash table in it to assemble packets into flows. It is a known problem that one CPU core is mostly used by the flow assembling thread. 

I think this part of code needs some optimisation. As I known, the tstat (http://tstat.polito.it/software.php) performs excellently on this side. But that is maybe because tstat just remembers the statistics of flow rather than the packet chains of the flow.

This tools is good at experimental or research aim. I do not recommend to use it directly in production, at least, for now. I will work on this problem later. :-)

Xiaming

**Comment by julsemaan** [comment]
Thanks for the quick answer
